version: '3.8'

services:
  app:
    image: nginx
    container_name: server-app
    # working_dir: /app
    ports:
      - 80:80
      - 8090:80
      - 8080:8080
      - 8001:8001
      - 8002:8002
      - 8003:8003
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./html/servico1:/usr/share/nginx/html/servico1
      - ./html/servico2:/usr/share/nginx/html/servico2
      - ./logs:/var/log/nginx
    entrypoint: sh -c "nginx -g 'daemon off;'"
    networks:
      - local

  # php-app:
  #   image: php:8.1.0
  #   container_name: server-php
    # working_dir: /app
    # ports:
    #   - 8000:8000
    # entrypoint: sh -c "php -S 0.0.0.0:8000"
    # networks:
    #   - local

networks:
  local:
